alkanza/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^alkanza/', include('rest_app.urls', namespace='alkanza', app_name='alkanza')),

]

rest_app/urls.py
from django.conf.urls import url
from rest_app import views

urlpatterns = [
    url(r'^list_repos/$', views.ListRepos.as_view(), name='list_repos'),
    url(r'^list_repos_db/$', views.ListReposDB.as_view(), name='list_repos_db'),

    ]

rest_app/models.py
from django.db import models

# Create your models here.


class Repository(models.Model):
    id_repo = models.CharField(max_length=150, blank=True)
    name_repo = models.CharField(max_length=150, blank=True)

rest_app/views.py
import mimetypes

import requests
import json
from django.core import serializers
from django.views.generic.base import TemplateView
from django.views.generic.list import ListView
from rest_app.models import Repository
from django.http.response import HttpResponse


# Create your views here.


class ListRepos(TemplateView):
    template_name = 'list_repos.html'

    def get_context_data(self, **kwargs):
        response = requests.get(
                'https://api.github.com/search/repositories?q=stars:%3E1+user&location:colombia&sort=stars&order=desc&page=1&per_page=10')
        data = json.loads(response.text)
        context_data = super(ListRepos, self).get_context_data(**kwargs)
        context_data['customer_data_list'] = data.get('items')
        repository = Repository.objects.all()

        if not repository.exists():
            for r in context_data['customer_data_list']:
                p = Repository(id_repo=r.get('id'), name_repo=r.get('name'))
                p.save()

        return context_data


class ListReposDB(ListView):
    template_name = 'list_repos.html'
    model = Repository

    def get(self, request, *args, **kwargs):
        repos = Repository.objects.all()
        data = serializers.serialize('json', repos, fields=('id_repo', 'name_repo'))
        return HttpResponse(data, content_type='application/json')

rest_app/templates/index.html
{% load staticfiles i18n %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Freelancer - Start Bootstrap Theme</title>

    {% block css %}

        <!-- Bootstrap Core CSS -->
        <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

        <!-- Theme CSS -->
        <link href="{% static 'css/freelancer.min.css' %}" rel="stylesheet">

        <!-- Custom Fonts -->
        <link href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
        <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet"
              type="text/css">

    {% endblock %}
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body id="page-top" class="index">

<!-- Navigation -->
<nav id="mainNav" class="navbar navbar-default navbar-fixed-top navbar-custom">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header page-scroll">
            <button type="button" class="navbar-toggle" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
            </button>
            <a class="navbar-brand" href="#page-top">Start Bootstrap</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li class="hidden">
                    <a href="#page-top"></a>
                </li>
                <li class="page-scroll">
                    <a href="#portfolio">Portfolio</a>
                </li>
                <li class="page-scroll">
                    <a href="#about">About</a>
                </li>
                <li class="page-scroll">
                    <a href="#contact">Contact</a>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>



<!-- Header -->
<header>


    <div class="container">
        <div class="row">
            {% block main2 %}
    <h1>Alkanza</h1>
            {% endblock %}

        </div>
    </div>
</header>
<br>
{% block main %}


{% endblock %}

<!-- Footer -->
<footer class="text-center">
    <div class="footer-above">
        <div class="container">
            <div class="row">
                <div class="footer-col col-md-4">
                    <h3>Location</h3>
                    <p>3481 Melrose Place
                        <br>Beverly Hills, CA 90210</p>
                </div>
                <div class="footer-col col-md-4">
                    <h3>Around the Web</h3>
                    <ul class="list-inline">
                        <li>
                            <a href="#" class="btn-social btn-outline"><i class="fa fa-fw fa-facebook"></i></a>
                        </li>
                        <li>
                            <a href="#" class="btn-social btn-outline"><i class="fa fa-fw fa-google-plus"></i></a>
                        </li>
                        <li>
                            <a href="#" class="btn-social btn-outline"><i class="fa fa-fw fa-twitter"></i></a>
                        </li>
                        <li>
                            <a href="#" class="btn-social btn-outline"><i class="fa fa-fw fa-linkedin"></i></a>
                        </li>
                        <li>
                            <a href="#" class="btn-social btn-outline"><i class="fa fa-fw fa-dribbble"></i></a>
                        </li>
                    </ul>
                </div>
                <div class="footer-col col-md-4">
                    <h3>About Freelancer</h3>
                    <p>Freelance is a free to use, open source Bootstrap theme created by <a
                            href="http://startbootstrap.com">Start Bootstrap</a>.</p>
                </div>
            </div>
        </div>
    </div>
    <div class="footer-below">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    Copyright &copy; Your Website 2016
                </div>
            </div>
        </div>
    </div>
</footer>

<!-- Scroll to Top Button (Only visible on small and extra-small screen sizes) -->
<div class="scroll-top page-scroll hidden-sm hidden-xs hidden-lg hidden-md">
    <a class="btn btn-primary" href="#page-top">
        <i class="fa fa-chevron-up"></i>
    </a>
</div>

{% block js %}

    <!-- jQuery -->

    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>

    <!-- Plugin JavaScript -->
    <!--<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script> -->

    <!-- Contact Form JavaScript -->
    <script src="{% static 'js/jqBootstrapValidation.js' %}"></script>
    <script src="{% static 'js/contact_me.js' %}"></script>

    <!-- Theme JavaScript -->
    <script src="{% static 'js/freelancer.min.js' %}"></script>

{% endblock %}

</body>

</html>

rest_app/templates/list_repos.html
{% extends "index.html" %}
{% load i18n %}
{% load staticfiles %}

{% block main %}
    <h1>{% trans 'Repositories' %}</h1>
    <div id="search" class="col-lg-12">
        <button id="load" class="btn btn-primary">{% trans 'load repos from db' %}</button>
    </div>
<br>
    <div>
        <table class="table table-striped">

            <thead>
            <th>#</th>
            <th>{% trans 'id' %}</th>
            <th>{% trans 'name' %}</th>

            </thead>
            <tbody>
            {% for data_costumer in customer_data_list %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ data_costumer.id }}</td>
                    <td>{{ data_costumer.name }}</td>

                </tr>
            {% endfor %}
            </tbody>

        </table>

        <h1>{% trans 'Repos From DB' %}</h1>
        <table class="table table-striped">
            <thead>
            <th>{% trans 'id' %}</th>
            <th>{% trans 'name' %}</th>

            </thead>

            <tbody id="repos">

            </tbody>


        </table>
    </div>
{% endblock %}

{% block js %}
    {{ block.super }}

    <script>

        $('#search').on('click', '#load', function () {

            $.get('{% url "alkanza:list_repos_db" %}', function (data) {
                var html = "";
                for (var i = 0; i < data.length; i++) {
                    html += "<tr><td>" + data[i].fields.id_repo + "</td><td>" + data[i].fields.name_repo + "</td><tr>";
                }

                $('#repos').html(html);
            });
        });


    </script>

{% endblock %}